apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-tqkv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-tqkv
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-tqkv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-tqkv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-tqkv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pudf-tenant/status-quarkus-io/statusquarkusio-tqkv@sha256:2e952055536435750a3bf7529d6ccf5613d0af7a5264ee6e8a2d8fa5d3060233
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
